#!/usr/bin/env bash
#
# verify:audit-phase2 — runs the six Phase-2 audit scripts in sequence.
#
# Per AUDIT_STRATEGY_MERGED.md §5, this is NOT wired into verify:full
# yet. It is a separately-callable gate that surfaces findings under
# the .verify/ directory. CI can opt into it once the findings have
# been triaged.
#
# Exit code:
#   0 — every script exited 0 AND every JSON artifact has empty findings.
#   1 — at least one script exited non-zero OR an artifact has findings.
#
# Output: per-script .verify/<name>.json + .verify/<name>.md, plus a
#         consolidated AUDIT_FINDINGS_PHASE2.md generated by the
#         caller (e.g. the audit task). This wrapper does NOT write
#         the consolidated report — that's the operator's call.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

SCRIPTS=(
  "scripts/audit_symmetry_matrix.py"
  "scripts/audit_invariants_pinned.py"
  "scripts/audit_negative_space.py"
  "scripts/harness/clock_freeze.py"
  "scripts/harness/parity_assert.py self-test --sandbox"
  "scripts/harness/poison_outbox.py drain-test --db /tmp/luna_phase2_poison.sqlite"
)

OVERALL_RC=0

for entry in "${SCRIPTS[@]}"; do
  echo "=== $entry ==="
  # shellcheck disable=SC2086
  python3 $entry --quiet 2>&1 || OVERALL_RC=$?
done

# Audit JSON sweep — any findings in any artifact mean fail.
mapfile -t artifacts < <(find .verify -maxdepth 1 -name 'audit_*.json' -o -name 'parity_assert.json' -o -name 'poison_outbox.json' 2>/dev/null | sort)
for art in "${artifacts[@]}"; do
  if [[ ! -f "$art" ]]; then
    continue
  fi
  count=$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); f=d.get('findings',[]); print(len(f))" "$art" 2>/dev/null || echo "0")
  if [[ "$count" -gt 0 ]]; then
    echo "[FAIL] $art has $count findings"
    OVERALL_RC=1
  else
    echo "[OK]   $art clean"
  fi
done

exit "$OVERALL_RC"
