#!/usr/bin/env bash
# scripts/verify/mutation-baseline.sh — One-shot mutation baseline for TS + Py.
#
# Usage:
#   bash scripts/verify/mutation-baseline.sh
#
# Runs every Stryker config registered in scripts/mutation/run.sh plus the
# mutmut Python gate, then emits docs/audit/MUTATION_BASELINE_<date>.md with:
#   - Headline total mutation scores (TS + Py)
#   - Per-config breakdown
#   - Worst-10 test files (lowest kill rate) with recommended actions
#
# This is a SLOW operation (30-60 min). Designed for one-off baseline
# capture only — NOT for CI. Writes all intermediate artifacts to
# .verify/ and reports/mutation/ exactly as the normal gate does.
#
# Constraints:
#   - Never uses --no-verify or --skip-python (full pass)
#   - Never pushes to git
#   - Safe to run in a git worktree
#
# Reproducibility:
#   bash scripts/verify/mutation-baseline.sh
#   # Requires: pnpm install + hardware/live-shelf/.venv with mutmut

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

BASELINE_DATE="${BASELINE_DATE:-$(date +%Y-%m-%d)}"
OUTFILE="$REPO_ROOT/docs/audit/MUTATION_BASELINE_${BASELINE_DATE}.md"

echo "[baseline] Starting full mutation baseline — $(date -u)" >&2
echo "[baseline] TS: all 3 Stryker configs (extensions + mcp-worker + web-shared)" >&2
echo "[baseline] Py: mutmut against hardware/live-shelf/server/ contract surface" >&2
echo "[baseline] Output → $OUTFILE" >&2
echo "" >&2

# Run full gate (TS + Python)
bash "$REPO_ROOT/scripts/mutation/run.sh"
GATE_EXIT=$?

echo "" >&2
echo "[baseline] Gate exit=$GATE_EXIT. Generating baseline report..." >&2

# Read the combined artifact
ARTIFACT="$REPO_ROOT/.verify/mutation.json"
PYTHON_ARTIFACT="$REPO_ROOT/.verify/mutation-python.json"

if [[ ! -f "$ARTIFACT" ]]; then
  echo "[baseline] ERROR: $ARTIFACT not found — gate did not complete" >&2
  exit 1
fi

node --input-type=module - <<'NODE' "$ARTIFACT" "$PYTHON_ARTIFACT" "$OUTFILE" "$BASELINE_DATE" "$GATE_EXIT"
import fs from 'node:fs';

const [artifactPath, pythonArtifactPath, outfile, baselineDate, exitRaw] = process.argv.slice(2);
const gateExit = Number(exitRaw);

const agg = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));

// Load Python artifact if present for per-file data
let pyArtifact = null;
try { pyArtifact = JSON.parse(fs.readFileSync(pythonArtifactPath, 'utf8')); } catch {}

const allFiles = agg.files || [];

// Sort by score_pct ascending (nulls last)
const sorted = [...allFiles].sort((a, b) => {
  if (a.score_pct === null && b.score_pct === null) return 0;
  if (a.score_pct === null) return 1;
  if (b.score_pct === null) return 1;
  return a.score_pct - b.score_pct;
});

const worst10 = sorted.slice(0, 10);

const s = agg.summary;
const tsScore = (() => {
  // Derive TS-only score from perFile entries that are NOT python
  const tsFiles = allFiles.filter(f => f.runtime !== 'python');
  const killed = tsFiles.reduce((acc, f) => acc + (f.killed || 0) + (f.timeout || 0), 0);
  const survived = tsFiles.reduce((acc, f) => acc + (f.survived || 0) + (f.noCovered || 0), 0);
  const valid = killed + survived;
  return valid > 0 ? ((killed / valid) * 100).toFixed(2) : 'n/a';
})();

const pyScore = agg.runtimes?.python?.score_pct ?? pyArtifact?.summary?.overall_score_pct ?? 'n/a';
const overallScore = s?.overall_score_pct ?? 'n/a';

const recommendAction = (f) => {
  const sc = f.score_pct;
  if (sc === null) return 'Add tests — no valid mutants reached (NoCoverage dominant)';
  if (sc < 20) return 'REWRITE: test file is nearly non-functional; mutants survive unchallenged';
  if (sc < 40) return 'CRITICAL: below break threshold — add meaningful assertions immediately';
  if (sc < 60) return 'ADD ASSERTIONS: surpasses break but below high watermark; strengthen checks';
  if (sc < 80) return 'IMPROVE: moderate coverage — add edge-case assertions to lift score';
  return 'MONITOR: acceptable score but room to improve boundary testing';
};

const fmtScore = (sc) => sc === null ? 'n/a (NoCoverage)' : `${sc}%`;
const fmtFile = (f) => f.file.length > 80 ? '...' + f.file.slice(-77) : f.file;

const lines = [];
lines.push(`# Mutation Baseline — ${baselineDate}`);
lines.push('');
lines.push('Generated by `scripts/verify/mutation-baseline.sh`. Full pass (no sampling).');
lines.push('');
lines.push(`**Gate status:** ${gateExit === 0 ? 'PASS' : 'FAIL'} (exit ${gateExit})`);
lines.push('');
lines.push('## Summary Scores');
lines.push('');
lines.push('| Runtime | Score | Killed | Survived | Timeout | NoCoverage |');
lines.push('|---------|-------|--------|----------|---------|------------|');
lines.push(`| TypeScript (all configs) | ${tsScore}% | ${s.killed} | ${s.survived} | ${s.timeout} | ${s.no_coverage} |`);
lines.push(`| Python (mutmut) | ${typeof pyScore === 'number' ? pyScore + '%' : pyScore} | ${pyArtifact?.summary?.killed ?? '-'} | ${pyArtifact?.summary?.survived ?? '-'} | ${pyArtifact?.summary?.timeout ?? '-'} | ${pyArtifact?.summary?.no_tests ?? '-'} |`);
lines.push(`| **Combined** | **${overallScore}%** | | | | |`);
lines.push('');
lines.push('## Per-Config Breakdown');
lines.push('');
const configGroups = {};
for (const f of allFiles) {
  const k = f.config || 'unknown';
  if (!configGroups[k]) configGroups[k] = { killed: 0, survived: 0, timeout: 0, noCov: 0, files: 0 };
  configGroups[k].killed += (f.killed || 0) + (f.timeout || 0);
  configGroups[k].survived += (f.survived || 0) + (f.noCovered || 0);
  configGroups[k].files++;
}
lines.push('| Config | Files | Kill Rate |');
lines.push('|--------|-------|-----------|');
for (const [cfg, d] of Object.entries(configGroups)) {
  const valid = d.killed + d.survived;
  const score = valid > 0 ? ((d.killed / valid) * 100).toFixed(2) + '%' : 'n/a';
  lines.push(`| \`${cfg}\` | ${d.files} | ${score} |`);
}
lines.push('');
lines.push('## Worst-10 Test Files (Lowest Kill Rate)');
lines.push('');
lines.push('Sorted ascending by mutation kill rate. These are the highest-priority targets');
lines.push('for test quality improvements.');
lines.push('');
lines.push('| # | File | Kill Rate | Killed | Survived | NoCoverage | Recommended Action |');
lines.push('|---|------|-----------|--------|----------|------------|-------------------|');
for (let i = 0; i < worst10.length; i++) {
  const f = worst10[i];
  const action = recommendAction(f);
  lines.push(
    `| ${i + 1} | \`${fmtFile(f)}\` | ${fmtScore(f.score_pct)} | ${f.killed} | ${f.survived} | ${f.noCovered ?? 0} | ${action} |`
  );
}
lines.push('');
lines.push('## Reproducibility');
lines.push('');
lines.push('```bash');
lines.push('# Full baseline (30-60 min):');
lines.push('bash scripts/verify/mutation-baseline.sh');
lines.push('');
lines.push('# TS only (skip Python gate):');
lines.push('bash scripts/mutation/run.sh --skip-python');
lines.push('');
lines.push('# Python only (from repo root):');
lines.push('bash scripts/mutation/python.sh');
lines.push('```');
lines.push('');
lines.push(`_Date: ${baselineDate}. Artifacts: \`.verify/mutation.json\`, \`.verify/mutation-python.json\`._`);

fs.writeFileSync(outfile, lines.join('\n') + '\n');
console.error(`[baseline] wrote ${outfile}`);
NODE

echo "[baseline] Done. Report: $OUTFILE" >&2
exit "$GATE_EXIT"
