-- Catch-all delta-capture model — schema scaffolding.
--
-- CONTEXT (2026-04-27):
--   The catch-all scale (scale-02 / kind='catch_all') is being redesigned
--   from a "secondary single-item shelf" to a **delta-capture
--   measurement station**. Workflow: user puts an item on, system
--   measures (first event); user takes it off, eats some, puts it back
--   on; system measures again (second event); cloud writes food_logs
--   for the consumed delta and updates lot qty.
--
--   Today the cloud's stock_lots.in_flight_since/pickup_event_id columns
--   are used to mark "this lot is off the shelf and expected back" —
--   shared between live_shelf REMOVE events and (post-redesign) catch_all
--   first-measurement events. Without a discriminator, the live_shelf
--   in-flight reaper that ZEROs qty would also reap catch_all in-flight
--   rows (which should KEEP their qty per the new model). Adding
--   ``in_flight_kind`` separates the two state machines cleanly while
--   reusing all the existing in-flight infrastructure (pickup_event_id,
--   the in_flight_since index, the resolve_add_to_shelf_lot lookup).
--
-- DESIGN:
--   1. Add ``stock_lots.in_flight_kind TEXT`` with a CHECK constraint
--      (``'live_shelf'`` | ``'catch_all'`` | NULL).
--   2. Add ``stock_lots.pickup_weight_g NUMERIC(10,3)`` so the second
--      catch-all measurement can compute the weight delta against the
--      first-measurement reading. Reuse the same column for the existing
--      live_shelf in-flight pickup snapshot — it's already conceptually
--      there in shelf_event_log payloads, but having it on the lot
--      avoids a payload reparse on the apply path.
--   3. Backfill: every existing in_flight_since IS NOT NULL row is from
--      the live_shelf flow (only live_shelf has been writing
--      in_flight_since to date). UPDATE them to in_flight_kind =
--      'live_shelf' so the post-migration reaper can rely on the column
--      being non-NULL whenever in_flight_since is set.
--
-- INVARIANT (enforced by code, not DB):
--   ``in_flight_since IS NOT NULL`` ⇒ ``in_flight_kind IS NOT NULL``.
--   The DB CHECK only validates the value when present so apply paths
--   that pre-date this migration can still write NULL → NULL.
--
-- NON-GOALS:
--   * No new event_kind plumbing in this migration. The
--     ``catch_all_first_measurement`` and ``catch_all_second_measurement``
--     event_kinds land in the next migration (20260427130000) which
--     extends apply_shelf_event with their branches.
--   * No backfill of pickup_weight_g for historical in_flight rows; the
--     next pickup will populate it via the apply path.

BEGIN;

------------------------------------------------------------
-- 1. Schema additions
------------------------------------------------------------

ALTER TABLE chefbyte.stock_lots
  ADD COLUMN IF NOT EXISTS in_flight_kind  TEXT,
  ADD COLUMN IF NOT EXISTS pickup_weight_g NUMERIC(10,3);

-- CHECK constraint — drop the autogenerated CHECK if it slipped through
-- a prior partial run, then add by name so we can reason about it.
ALTER TABLE chefbyte.stock_lots
  DROP CONSTRAINT IF EXISTS stock_lots_in_flight_kind_check;
ALTER TABLE chefbyte.stock_lots
  ADD CONSTRAINT stock_lots_in_flight_kind_check
    CHECK (in_flight_kind IS NULL
           OR in_flight_kind IN ('live_shelf', 'catch_all'));

-- pickup_weight_g must be > 0 when present. NULL is the "no pickup
-- snapshot" sentinel.
ALTER TABLE chefbyte.stock_lots
  DROP CONSTRAINT IF EXISTS stock_lots_pickup_weight_g_check;
ALTER TABLE chefbyte.stock_lots
  ADD CONSTRAINT stock_lots_pickup_weight_g_check
    CHECK (pickup_weight_g IS NULL OR pickup_weight_g > 0);

------------------------------------------------------------
-- 2. Backfill existing in_flight rows
------------------------------------------------------------
-- Every row with in_flight_since IS NOT NULL today is from the
-- live_shelf flow. The catch_all in-flight semantic doesn't exist yet
-- (it lands with the apply_shelf_event branches in the next migration),
-- so anything currently in-flight is by definition live_shelf-style.

UPDATE chefbyte.stock_lots
   SET in_flight_kind = 'live_shelf'
 WHERE in_flight_since IS NOT NULL
   AND in_flight_kind IS NULL;

------------------------------------------------------------
-- 3. Index for the catch_all reaper
------------------------------------------------------------
-- Partial index — only catch_all in-flight rows. Used by the future
-- reaper RPC to scan for TTL-expired catch_all in-flight lots without
-- joining the much larger live_shelf in-flight set.

CREATE INDEX IF NOT EXISTS idx_stock_lots_catch_all_in_flight
  ON chefbyte.stock_lots (user_id, in_flight_since)
  WHERE in_flight_since IS NOT NULL AND in_flight_kind = 'catch_all';

COMMENT ON COLUMN chefbyte.stock_lots.in_flight_kind IS
  'Discriminator for the in-flight state machine. ''live_shelf'' = pickup '
  'from the live shelf, expected back, full qty consumed on pickup-close '
  'whole-lot resolution. ''catch_all'' = first measurement of a delta-'
  'capture session on the catch-all scale, qty already reflects the '
  'measured weight, second measurement records the delta. NULL when the '
  'lot is not in flight.';

COMMENT ON COLUMN chefbyte.stock_lots.pickup_weight_g IS
  'Weight in grams snapshot at the moment the lot entered an in-flight '
  'state. Live-shelf flow: weight at REMOVE time; catch-all flow: '
  'measured weight from the first catch-all event. Used by the second '
  'catch-all event to compute consumption delta. NULL when the lot is '
  'not in flight.';

COMMIT;
