-- Cloud-side handler for the manual-discard event.
--
-- CONTEXT (2026-04-27):
--   The Live Shelf Pi web UI has a per-lot "remove" (×) button at
--   /inventory. Until now it deleted the lot from Pi SQLite only; cloud
--   never heard about it, leaving stock_lots out of sync with the user's
--   intent (and any in_flight_since marker stuck on the cloud row
--   forever).
--
--   We need a propagation path from the Pi remove button to the cloud
--   that:
--     * Zeroes stock_lots.qty_containers
--     * Clears in_flight_since + pickup_event_id (so a stuck-in-flight
--       lot can be cleaned up by the user via the same button)
--     * Does NOT write a chefbyte.food_logs row
--     * Does NOT update macros for the day
--     * Marks last_update_source so audits can distinguish the
--       manual-discard origin from regular consumption
--
--   This is a *manual discard* — the user explicitly removes the lot
--   from inventory WITHOUT recording it as consumed (spilled,
--   expired-and-thrown-out, fed-to-pet, given-away, etc.). Reusing the
--   `consumed` event_kind with a `skip_macros` flag was rejected — see
--   decisions.md #44 — because it overloads consumed with macro-skip
--   logic and bleeds discard semantics into the consumption audit
--   trail. Adding a dedicated `discarded` kind keeps both event_kinds
--   honest.
--
-- DESIGN:
--   Extend apply_shelf_event with a new `discarded` branch (parallel to
--   the in_flight_pickup/in_flight_return early branches). The branch:
--     1. Validates the product belongs to the user (ownership guard).
--     2. Picks the most-recent qty>0 lot for the (user, product); falls
--        back to the most-recent in_flight lot when qty=0 (the stuck-
--        in-flight recovery case); falls back to the newest lot of any
--        qty as last resort.
--     3. UPDATE stock_lots SET qty_containers=0, in_flight_since=NULL,
--        pickup_event_id=NULL, last_update_source='manual_discard',
--        last_update_ts=p_occurred_at.
--     4. Returns applied=true with reason='discarded' (or
--        'discarded (idempotent no-op)' when the lot was already at
--        qty=0 and cleared).
--     5. NO food_logs insert. NO macro mutation.
--
--   Idempotency: shelf_event_log dedup on (user_id, client_event_id)
--   means a retry returns the cached result. A direct re-apply with a
--   new client_event_id but the lot already at qty=0 is also safe — the
--   UPDATE is a no-op write, and we still flip last_update_source/ts so
--   the audit trail records the discard intent.
--
-- NON-GOALS:
--   * Does NOT void or delete prior food_logs rows from earlier
--     consumed events on the same lot. Manual-discard is a forward
--     state change; historical macros stay logged.
--   * Does NOT mutate session_resolutions / shelf_event_log payloads
--     for events that already landed against this lot.
--   * Does NOT cascade to scale_pairings / live_shelf_devices.

BEGIN;

-- Extend the stock_lots.last_update_source CHECK constraint to accept
-- the new 'manual_discard' tag. The original constraint
-- (20260419010000_live_shelf.sql) limits values to (manual, live_shelf,
-- live_scale, catch_all). We add 'manual_discard' so the discard branch
-- below can stamp the audit-friendly origin.
--
-- The constraint is unnamed in the parent migration (Postgres autogenerates
-- ``stock_lots_last_update_source_check`` per column-level CHECK), so we
-- DROP by the autogenerated name and ADD a renamed constraint
-- (same predicate plus the new literal). IF EXISTS makes the migration
-- safe on local resets where the constraint name might differ.
ALTER TABLE chefbyte.stock_lots
  DROP CONSTRAINT IF EXISTS stock_lots_last_update_source_check;
ALTER TABLE chefbyte.stock_lots
  ADD CONSTRAINT stock_lots_last_update_source_check
    CHECK (last_update_source IS NULL
           OR last_update_source IN (
             'manual',
             'manual_discard',
             'live_shelf',
             'live_scale',
             'catch_all'
           ));

-- Drop the existing 10-arg overload from migration 20260425080000 so we
-- can recreate it with the new branch. CREATE OR REPLACE is normally
-- enough but we keep the explicit DROP pattern for symmetry with the
-- in_flight_pickup migration (which dropped a 9-arg overload first to
-- avoid ambiguity).
--
-- Note: 20260427010000 (in_flight_pickup_resolve_whole_lot) uses
-- CREATE OR REPLACE, so the body below MUST preserve every change from
-- BOTH 20260425080000 AND 20260427010000. Diffed line-by-line at write
-- time; the only added code is the discarded branch and the early-
-- branch IF clause that routes to it.

CREATE OR REPLACE FUNCTION private.apply_shelf_event(
  p_user_id         UUID,
  p_device_id       UUID,
  p_scale_id        TEXT,
  p_kind            TEXT,
  p_event_kind      TEXT,
  p_product_id      UUID,
  p_delta_g         NUMERIC,
  p_occurred_at     TIMESTAMPTZ,
  p_client_event_id TEXT,
  p_pi_event_id     TEXT DEFAULT NULL
) RETURNS chefbyte.shelf_event_result
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_existing_applied BOOLEAN;
  v_existing_lot     UUID;
  v_existing_reason  TEXT;
  v_log_id           UUID;
  v_net_g            NUMERIC;
  v_svg_per          NUMERIC;
  v_cal              NUMERIC;
  v_carbs            NUMERIC;
  v_protein          NUMERIC;
  v_fat              NUMERIC;
  v_delta_c          NUMERIC;
  v_lot_id           UUID;
  v_loc_id           UUID;
  v_tz               TEXT;
  v_dsh              INTEGER;
  v_logical_date     DATE;
  v_new_qty          NUMERIC;
  v_servings         NUMERIC;
  v_insert_qty       NUMERIC;
  v_lot_src          TEXT;
  v_lot_ts           TIMESTAMPTZ;
  v_result           chefbyte.shelf_event_result;
  v_pi_event_uuid    UUID;
  v_pickup_lot_id    UUID;
  v_already_zero     BOOLEAN;
BEGIN
  IF p_kind IS NULL OR p_kind NOT IN ('live_shelf','live_scale','catch_all') THEN
    RAISE EXCEPTION 'invalid kind: %', p_kind USING ERRCODE = '22023';
  END IF;
  IF p_client_event_id IS NULL OR char_length(p_client_event_id) = 0 THEN
    RAISE EXCEPTION 'client_event_id required' USING ERRCODE = '22023';
  END IF;

  INSERT INTO chefbyte.shelf_event_log (
    user_id, device_id, client_event_id, payload, applied, reason, pi_event_id
  ) VALUES (
    p_user_id, p_device_id, p_client_event_id,
    jsonb_build_object(
      'scale_id', p_scale_id,
      'kind', p_kind,
      'event_kind', p_event_kind,
      'product_id', p_product_id,
      'delta_g', p_delta_g,
      'occurred_at', p_occurred_at,
      'pi_event_id', p_pi_event_id
    ),
    false, 'pending', p_pi_event_id
  )
  ON CONFLICT (user_id, client_event_id) DO NOTHING
  RETURNING event_id INTO v_log_id;

  IF v_log_id IS NULL THEN
    UPDATE chefbyte.shelf_event_log
       SET pi_event_id = p_pi_event_id
     WHERE user_id = p_user_id
       AND client_event_id = p_client_event_id
       AND pi_event_id IS NULL
       AND p_pi_event_id IS NOT NULL;

    SELECT applied, resolved_lot_id, reason
      INTO v_existing_applied, v_existing_lot, v_existing_reason
      FROM chefbyte.shelf_event_log
     WHERE user_id = p_user_id AND client_event_id = p_client_event_id;
    v_result := ROW(v_existing_lot, v_existing_applied, v_existing_reason);
    RETURN v_result;
  END IF;

  ------------------------------------------------------------
  -- Early branch: in_flight_pickup / in_flight_return
  -- (20260425080000 — no net_weight_g / food_logs side effects)
  ------------------------------------------------------------

  IF p_event_kind IN ('in_flight_pickup','in_flight_return') THEN
    -- Guard: product must exist for this user (ownership check).
    IF NOT EXISTS (
      SELECT 1 FROM chefbyte.products
       WHERE product_id = p_product_id AND user_id = p_user_id
    ) THEN
      v_result := ROW(NULL::UUID, false, 'product not found');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    -- Parse Pi event id into UUID if it looks well-formed.
    IF p_pi_event_id IS NOT NULL AND char_length(p_pi_event_id) = 36 THEN
      BEGIN
        v_pi_event_uuid := p_pi_event_id::uuid;
      EXCEPTION WHEN OTHERS THEN
        v_pi_event_uuid := NULL;
      END;
    ELSE
      v_pi_event_uuid := NULL;
    END IF;

    IF p_event_kind = 'in_flight_pickup' THEN
      SELECT lot_id INTO v_lot_id
        FROM chefbyte.stock_lots
       WHERE user_id = p_user_id
         AND product_id = p_product_id
         AND qty_containers > 0
       ORDER BY
         CASE WHEN last_update_source = p_kind THEN 0 ELSE 1 END,
         expires_on ASC NULLS LAST,
         last_update_ts DESC NULLS LAST
       LIMIT 1;

      IF v_lot_id IS NULL THEN
        SELECT lot_id INTO v_lot_id
          FROM chefbyte.stock_lots
         WHERE user_id = p_user_id
           AND product_id = p_product_id
           AND in_flight_since IS NOT NULL
         ORDER BY in_flight_since DESC
         LIMIT 1;
      END IF;

      IF v_lot_id IS NULL THEN
        SELECT lot_id INTO v_lot_id
          FROM chefbyte.stock_lots
         WHERE user_id = p_user_id
           AND product_id = p_product_id
         ORDER BY last_update_ts DESC NULLS LAST, created_at DESC
         LIMIT 1;
      END IF;

      IF v_lot_id IS NULL THEN
        v_result := ROW(NULL::UUID, false, 'no lot for product to mark in_flight');
        UPDATE chefbyte.shelf_event_log
           SET applied = v_result.applied,
               resolved_lot_id = v_result.resolved_lot_id,
               reason = v_result.reason
         WHERE event_id = v_log_id;
        RETURN v_result;
      END IF;

      UPDATE chefbyte.stock_lots
         SET in_flight_since = p_occurred_at,
             pickup_event_id = COALESCE(v_pi_event_uuid, pickup_event_id),
             last_update_ts  = p_occurred_at
       WHERE lot_id = v_lot_id
         AND user_id = p_user_id;

      v_result := ROW(v_lot_id, true, 'in_flight_since stamped');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    -- p_event_kind = 'in_flight_return'
    SELECT lot_id INTO v_lot_id
      FROM chefbyte.stock_lots
     WHERE user_id = p_user_id
       AND product_id = p_product_id
       AND in_flight_since IS NOT NULL
     ORDER BY in_flight_since DESC
     LIMIT 1;

    IF v_lot_id IS NULL THEN
      v_result := ROW(NULL::UUID, true, 'no in_flight lot to clear (no-op)');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    UPDATE chefbyte.stock_lots
       SET in_flight_since = NULL,
           pickup_event_id = NULL,
           last_update_ts  = p_occurred_at
     WHERE lot_id = v_lot_id
       AND user_id = p_user_id;

    v_result := ROW(v_lot_id, true, 'in_flight_since cleared');
    UPDATE chefbyte.shelf_event_log
       SET applied = v_result.applied,
           resolved_lot_id = v_result.resolved_lot_id,
           reason = v_result.reason
     WHERE event_id = v_log_id;
    RETURN v_result;
  END IF;

  ------------------------------------------------------------
  -- Early branch: discarded
  -- (NEW 20260427020000 — manual user discard from Pi UI; zeros qty,
  -- clears in_flight_since/pickup_event_id, does NOT write food_logs.)
  ------------------------------------------------------------

  IF p_event_kind = 'discarded' THEN
    -- Guard: product must exist for this user (ownership check).
    IF NOT EXISTS (
      SELECT 1 FROM chefbyte.products
       WHERE product_id = p_product_id AND user_id = p_user_id
    ) THEN
      v_result := ROW(NULL::UUID, false, 'product not found');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    -- Lot pick: prefer qty>0 (the "normal" discard case). Match the
    -- in_flight_pickup ordering so live_shelf vs live_scale lots don't
    -- spuriously cross-contaminate.
    SELECT lot_id INTO v_lot_id
      FROM chefbyte.stock_lots
     WHERE user_id = p_user_id
       AND product_id = p_product_id
       AND qty_containers > 0
     ORDER BY
       CASE WHEN last_update_source = p_kind THEN 0 ELSE 1 END,
       expires_on ASC NULLS LAST,
       last_update_ts DESC NULLS LAST
     LIMIT 1;

    -- Fallback 1: stuck-in-flight lot (the manual-recovery affordance).
    -- A lot can divergently sit at qty=0 + in_flight_since IS NOT NULL
    -- when an in_flight_pickup landed but the matching consumed event
    -- arrived with the wrong delta_g (legacy bug, fixed in
    -- 20260427010000). User hits the × button on /inventory; we want to
    -- clean up the in-flight marker so the row stops looking stuck.
    IF v_lot_id IS NULL THEN
      SELECT lot_id INTO v_lot_id
        FROM chefbyte.stock_lots
       WHERE user_id = p_user_id
         AND product_id = p_product_id
         AND in_flight_since IS NOT NULL
       ORDER BY in_flight_since DESC
       LIMIT 1;
    END IF;

    -- Fallback 2: newest lot of any qty for this product. Idempotent
    -- by design — re-discarding an already-zeroed-and-cleared lot is
    -- a no-op write (UPDATE still bumps last_update_ts).
    IF v_lot_id IS NULL THEN
      SELECT lot_id INTO v_lot_id
        FROM chefbyte.stock_lots
       WHERE user_id = p_user_id
         AND product_id = p_product_id
       ORDER BY last_update_ts DESC NULLS LAST, created_at DESC
       LIMIT 1;
    END IF;

    IF v_lot_id IS NULL THEN
      v_result := ROW(NULL::UUID, true, 'no lot for product (idempotent no-op)');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    -- Detect already-zeroed-and-cleared so we can return a
    -- distinguishable reason for the audit trail. The UPDATE itself
    -- runs unconditionally — last_update_ts/source still flip so
    -- audits show the discard intent.
    SELECT (qty_containers = 0 AND in_flight_since IS NULL
            AND pickup_event_id IS NULL)
      INTO v_already_zero
      FROM chefbyte.stock_lots
     WHERE lot_id = v_lot_id;

    UPDATE chefbyte.stock_lots
       SET qty_containers     = 0,
           in_flight_since    = NULL,
           pickup_event_id    = NULL,
           last_update_source = 'manual_discard',
           last_update_ts     = p_occurred_at
     WHERE lot_id = v_lot_id
       AND user_id = p_user_id;

    v_result := ROW(
      v_lot_id,
      true,
      CASE WHEN COALESCE(v_already_zero, false)
           THEN 'discarded (idempotent no-op)'
           ELSE 'discarded' END
    );
    UPDATE chefbyte.shelf_event_log
       SET applied = v_result.applied,
           resolved_lot_id = v_result.resolved_lot_id,
           reason = v_result.reason
     WHERE event_id = v_log_id;
    RETURN v_result;
  END IF;

  ------------------------------------------------------------
  -- Legacy body — preserved verbatim from 20260427010000.
  -- (consumed/depleted with pickup-resolve detection,
  --  added/refilled paths.)
  ------------------------------------------------------------

  SELECT net_weight_g, servings_per_container,
         calories_per_serving, carbs_per_serving,
         protein_per_serving, fat_per_serving
    INTO v_net_g, v_svg_per, v_cal, v_carbs, v_protein, v_fat
    FROM chefbyte.products
   WHERE product_id = p_product_id AND user_id = p_user_id;

  IF NOT FOUND THEN
    v_result := ROW(NULL::UUID, false, 'product not found');
    UPDATE chefbyte.shelf_event_log
       SET applied = v_result.applied,
           resolved_lot_id = v_result.resolved_lot_id,
           reason = v_result.reason
     WHERE event_id = v_log_id;
    RETURN v_result;
  END IF;

  IF v_net_g IS NULL OR v_net_g <= 0 THEN
    v_result := ROW(NULL::UUID, false, 'product missing net_weight_g');
    UPDATE chefbyte.shelf_event_log
       SET applied = v_result.applied,
           resolved_lot_id = v_result.resolved_lot_id,
           reason = v_result.reason
     WHERE event_id = v_log_id;
    RETURN v_result;
  END IF;

  v_delta_c := p_delta_g / v_net_g;

  SELECT timezone, day_start_hour INTO v_tz, v_dsh
    FROM hub.profiles WHERE user_id = p_user_id;
  IF v_tz  IS NULL THEN v_tz  := 'UTC'; END IF;
  IF v_dsh IS NULL THEN v_dsh := 0;     END IF;
  v_logical_date := private.get_logical_date(now(), v_tz, v_dsh);

  IF p_event_kind IN ('consumed','depleted') THEN
    -- Pickup-resolve detection (20260427010000).
    -- If p_pi_event_id matches any lot's pickup_event_id for this
    -- (user, product), this consumed/depleted is RESOLVING the
    -- in-flight pickup → zero qty + clear marker regardless of delta_g.
    IF p_pi_event_id IS NOT NULL AND char_length(p_pi_event_id) = 36 THEN
      BEGIN
        v_pi_event_uuid := p_pi_event_id::uuid;
      EXCEPTION WHEN OTHERS THEN
        v_pi_event_uuid := NULL;
      END;
    ELSE
      v_pi_event_uuid := NULL;
    END IF;

    IF v_pi_event_uuid IS NOT NULL THEN
      SELECT lot_id INTO v_pickup_lot_id
        FROM chefbyte.stock_lots
       WHERE user_id = p_user_id
         AND product_id = p_product_id
         AND pickup_event_id = v_pi_event_uuid
       ORDER BY in_flight_since DESC NULLS LAST
       LIMIT 1;
    END IF;

    IF v_pickup_lot_id IS NOT NULL THEN
      v_lot_id := v_pickup_lot_id;
      -- Whole-lot zero out + clear in-flight marker.
      UPDATE chefbyte.stock_lots
         SET qty_containers     = 0,
             in_flight_since    = NULL,
             pickup_event_id    = NULL,
             last_update_source = p_kind,
             last_update_ts     = p_occurred_at
       WHERE lot_id = v_lot_id
       RETURNING qty_containers INTO v_new_qty;

      v_servings := ABS(v_delta_c) * COALESCE(v_svg_per, 0);
      IF v_servings > 0 THEN
        INSERT INTO chefbyte.food_logs
          (user_id, product_id, logical_date, qty_consumed, unit,
           calories, carbs, protein, fat, source_client_event_id)
        VALUES
          (p_user_id, p_product_id, v_logical_date, v_servings, 'serving',
           v_servings * COALESCE(v_cal,     0),
           v_servings * COALESCE(v_carbs,   0),
           v_servings * COALESCE(v_protein, 0),
           v_servings * COALESCE(v_fat,     0),
           p_client_event_id);
      END IF;

      v_result := ROW(v_lot_id, true, 'pickup_close_whole_lot');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    SELECT lot_id, last_update_source, last_update_ts
      INTO v_lot_id, v_lot_src, v_lot_ts
      FROM chefbyte.stock_lots
     WHERE user_id = p_user_id AND product_id = p_product_id
       AND qty_containers > 0
     ORDER BY expires_on ASC NULLS LAST
     LIMIT 1;

    IF v_lot_id IS NULL THEN
      v_result := ROW(NULL::UUID, false, 'no lot with stock to decrement');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    IF v_lot_src = 'manual' AND v_lot_ts IS NOT NULL
       AND v_lot_ts > p_occurred_at THEN
      v_result := ROW(v_lot_id, false, 'stale: manual edit is newer');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    IF p_event_kind = 'depleted' THEN
      UPDATE chefbyte.stock_lots
         SET qty_containers     = 0,
             last_update_source = p_kind,
             last_update_ts     = p_occurred_at
       WHERE lot_id = v_lot_id
       RETURNING qty_containers INTO v_new_qty;
    ELSE
      UPDATE chefbyte.stock_lots
         SET qty_containers     = GREATEST(qty_containers + v_delta_c, 0),
             last_update_source = p_kind,
             last_update_ts     = p_occurred_at
       WHERE lot_id = v_lot_id
       RETURNING qty_containers INTO v_new_qty;
    END IF;

    v_servings := ABS(v_delta_c) * COALESCE(v_svg_per, 0);

    IF v_servings > 0 THEN
      INSERT INTO chefbyte.food_logs
        (user_id, product_id, logical_date, qty_consumed, unit,
         calories, carbs, protein, fat, source_client_event_id)
      VALUES
        (p_user_id, p_product_id, v_logical_date, v_servings, 'serving',
         v_servings * COALESCE(v_cal,     0),
         v_servings * COALESCE(v_carbs,   0),
         v_servings * COALESCE(v_protein, 0),
         v_servings * COALESCE(v_fat,     0),
         p_client_event_id);
    END IF;

    v_result := ROW(v_lot_id, true,
                    CASE WHEN p_event_kind = 'depleted' THEN 'depleted'
                         ELSE 'decremented' END);
    UPDATE chefbyte.shelf_event_log
       SET applied = v_result.applied,
           resolved_lot_id = v_result.resolved_lot_id,
           reason = v_result.reason
     WHERE event_id = v_log_id;
    RETURN v_result;

  ELSIF p_event_kind IN ('added','refilled') THEN
    IF p_kind IN ('live_shelf','live_scale') THEN
      SELECT location_id INTO v_loc_id
        FROM chefbyte.locations
       WHERE user_id = p_user_id
       ORDER BY created_at ASC
       LIMIT 1;

      IF v_loc_id IS NULL THEN
        v_result := ROW(NULL::UUID, false, 'user has no locations');
        UPDATE chefbyte.shelf_event_log
           SET applied = v_result.applied,
               resolved_lot_id = v_result.resolved_lot_id,
               reason = v_result.reason
         WHERE event_id = v_log_id;
        RETURN v_result;
      END IF;

      v_lot_id := private.resolve_add_to_shelf_lot(
        p_user_id, p_product_id, p_kind, v_loc_id,
        GREATEST(p_delta_g, 0), v_log_id, p_occurred_at
      );

      v_result := ROW(v_lot_id, true, 'resolved_add');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    -- Non-tracked (catch_all) path
    SELECT lot_id, last_update_source, last_update_ts
      INTO v_lot_id, v_lot_src, v_lot_ts
      FROM chefbyte.stock_lots
     WHERE user_id = p_user_id AND product_id = p_product_id
       AND qty_containers > 0
     ORDER BY created_at ASC
     LIMIT 1;

    IF v_lot_id IS NULL THEN
      SELECT location_id INTO v_loc_id
        FROM chefbyte.locations
       WHERE user_id = p_user_id
       ORDER BY created_at ASC
       LIMIT 1;

      IF v_loc_id IS NULL THEN
        v_result := ROW(NULL::UUID, false, 'user has no locations');
        UPDATE chefbyte.shelf_event_log
           SET applied = v_result.applied,
               resolved_lot_id = v_result.resolved_lot_id,
               reason = v_result.reason
         WHERE event_id = v_log_id;
        RETURN v_result;
      END IF;

      v_insert_qty := GREATEST(v_delta_c, 0);

      INSERT INTO chefbyte.stock_lots
        (user_id, product_id, location_id, qty_containers,
         last_update_source, last_update_ts)
      VALUES
        (p_user_id, p_product_id, v_loc_id, v_insert_qty, p_kind, p_occurred_at)
      RETURNING lot_id INTO v_lot_id;

      v_result := ROW(v_lot_id, true, 'new lot created');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    IF v_lot_src = 'manual' AND v_lot_ts IS NOT NULL
       AND v_lot_ts > p_occurred_at THEN
      v_result := ROW(v_lot_id, false, 'stale: manual edit is newer');
      UPDATE chefbyte.shelf_event_log
         SET applied = v_result.applied,
             resolved_lot_id = v_result.resolved_lot_id,
             reason = v_result.reason
       WHERE event_id = v_log_id;
      RETURN v_result;
    END IF;

    UPDATE chefbyte.stock_lots
       SET qty_containers     = GREATEST(qty_containers + v_delta_c, 0),
           last_update_source = p_kind,
           last_update_ts     = p_occurred_at,
           in_flight_since    = NULL,
           pickup_event_id    = NULL
     WHERE lot_id = v_lot_id
     RETURNING qty_containers INTO v_new_qty;

    v_result := ROW(v_lot_id, true, 'incremented');
    UPDATE chefbyte.shelf_event_log
       SET applied = v_result.applied,
           resolved_lot_id = v_result.resolved_lot_id,
           reason = v_result.reason
     WHERE event_id = v_log_id;
    RETURN v_result;

  ELSE
    v_result := ROW(NULL::UUID, false, 'unknown event_kind');
    UPDATE chefbyte.shelf_event_log
       SET applied = v_result.applied,
           resolved_lot_id = v_result.resolved_lot_id,
           reason = v_result.reason
     WHERE event_id = v_log_id;
    RETURN v_result;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION private.apply_shelf_event(
  UUID, UUID, TEXT, TEXT, TEXT, UUID, NUMERIC, TIMESTAMPTZ, TEXT, TEXT
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION private.apply_shelf_event(
  UUID, UUID, TEXT, TEXT, TEXT, UUID, NUMERIC, TIMESTAMPTZ, TEXT, TEXT
) TO service_role;

COMMENT ON FUNCTION private.apply_shelf_event(
  UUID, UUID, TEXT, TEXT, TEXT, UUID, NUMERIC, TIMESTAMPTZ, TEXT, TEXT
) IS
  'Cloud-side applier for Pi shelf events. Accepts consumed/depleted/added/'
  'refilled (existing) + in_flight_pickup/in_flight_return (added '
  '20260425080000) + discarded (added 20260427020000). The discarded '
  'branch zeros qty + clears in_flight marker WITHOUT writing food_logs '
  '(manual user discard from Pi /inventory remove button — no macro '
  'tracking by design). Idempotent via shelf_event_log '
  'UNIQUE(user_id, client_event_id).';

COMMIT;
